# Generated by Django 4.2.6 on 2023-11-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userwithkey_drowsinessevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='drowsinessevent',
            name='status',
            field=models.CharField(choices=[('W', 'Warning'), ('C', 'Critical'), ('B', 'Brake Activation'), ('AW', 'Alert from Warning'), ('AC', 'Alert from Critical'), ('AB', 'Alert from Brake Activation')], default='W', max_length=2),
        ),
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='0b7a66a673dc8104600615db76571972', max_length=100),
        ),
    ]
