# Generated by Django 4.2.6 on 2023-11-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_drowsinessevent_status_alter_userwithkey_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='12470dbd64feab0b4774b89f21eaa443', max_length=100),
        ),
    ]
