# Generated by Django 4.2.6 on 2023-11-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userwithkey_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='afe33df49b7fb0690552e5e019803e47', max_length=100),
        ),
    ]
