# Generated by Django 4.2.6 on 2023-11-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_userwithkey_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='2261ba4e73e59209e20a970d40f91781', max_length=100),
        ),
    ]
