# Generated by Django 4.2.6 on 2023-11-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_userwithkey_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='99b564671df11b7d19c5b63bd377d24a', max_length=100),
        ),
    ]
