# Generated by Django 4.2.6 on 2023-11-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_userwithkey_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithkey',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userwithkey',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='d318c96f3f0c92e88cf8ed5178bfb74a', max_length=100),
        ),
    ]
