# Generated by Django 4.2.6 on 2023-12-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_userwithkey_is_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='07969a9123663826573a2e553f6e2dac', max_length=100),
        ),
    ]
