# Generated by Django 4.2.6 on 2023-12-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_userwithkey_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='e77d53f25fbedb352f2df205049e35c7', max_length=100),
        ),
    ]
