# Generated by Django 4.2.6 on 2023-12-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_userwithkey_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drowsinessevent',
            name='status',
            field=models.CharField(choices=[('W', 'Warning'), ('C', 'Critical'), ('B', 'Brake Activation'), ('BD', 'Brake Deactivated')], default='W', max_length=2),
        ),
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='240add93a16467f14d51790215ad4634', max_length=100),
        ),
    ]
