# Generated by Django 4.2.6 on 2023-12-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_drowsinessevent_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drowsinessevent',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='02b7fc0f290f567149ca4bae73fac5cf', max_length=100),
        ),
    ]
