# Generated by Django 4.2.6 on 2023-12-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_drowsinessevent_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='fb1264685e792754c93c3a3607497da9', max_length=100),
        ),
    ]
