# Generated by Django 4.2.6 on 2023-12-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_userwithkey_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='61babfe6791f591a127e6bdde664f750', max_length=100),
        ),
    ]
