# Generated by Django 4.2.6 on 2023-12-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_userwithkey_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='52121aa2cd9a2a07b334b548a7b31987', max_length=100),
        ),
    ]
