# Generated by Django 4.2.6 on 2023-12-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_userwithkey_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='1d6be7303bc63244fa6956d40a904409', max_length=100),
        ),
    ]
