# Generated by Django 4.2.6 on 2023-12-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_userwithkey_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='9be179c465518536f820f5041d1eca73', max_length=100),
        ),
    ]
