# Generated by Django 4.2.6 on 2023-12-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_userwithkey_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='19620bab332f1ca02a959f415dbc3f8a', max_length=100),
        ),
    ]
