# Generated by Django 4.2.6 on 2023-12-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_userwithkey_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='386b69719462bd5354db3d5b11d0f9f8', max_length=100),
        ),
    ]
