# Generated by Django 4.2.6 on 2023-12-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_userwithkey_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='eaca7c96b428899696270dc1a35cdd81', max_length=100),
        ),
    ]
