# Generated by Django 4.2.6 on 2023-12-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_userwithkey_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithkey',
            name='secret_key',
            field=models.CharField(default='770f776b34ec78e9eac4754e2af90ca6', max_length=100),
        ),
    ]
